# Generated by Django 4.2 on 2023-05-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_alter_offer_address_of_delivery_alter_offer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
