# Generated by Django 4.0.1 on 2023-04-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_task_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hours',
            new_name='estimate_hours',
        ),
    ]
