# Generated by Django 4.0.1 on 2023-04-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_day_end_worker_day_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstasks',
            name='time_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workerstasks',
            name='time_start',
            field=models.DateField(auto_now=True),
        ),
    ]
