# Generated by Django 4.0.1 on 2023-04-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_workerstasks_time_end_workerstasks_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerstasks',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workerstasks',
            name='time_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
