# Generated by Django 4.0.1 on 2023-04-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_workerlogs_description_workerlogs_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='day_end',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='day_start',
        ),
        migrations.AlterField(
            model_name='workerlogs',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workerlogs',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workerstasks',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
