# Generated by Django 4.0.1 on 2023-04-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_worker_day_end_worker_day_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='day_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='day_start',
            field=models.TimeField(),
        ),
    ]
