# Generated by Django 4.0.1 on 2023-05-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_workerlogs_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('task_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workerstasks')),
            ],
        ),
    ]
