# Generated by Django 4.2 on 2023-05-27 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0018_taskappointment_status_alter_workerlogs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerschedule',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='workers.worker'),
        ),
    ]
