# Generated by Django 4.2 on 2023-05-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_alter_workerschedule_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlogs',
            name='type',
            field=models.CharField(choices=[('TA', 'Task appointed'), ('TD', 'Task done'), ('TC', 'Task status changed'), ('OC', 'Out of working place'), ('SL', 'Supervisor connection lost'), ('CL', 'Custom log')], default='CL', max_length=2),
        ),
    ]
